### ISSUE TITLE
Show "Hooks can only be called inside of the body of a function component." after start

### ISSUE THREAD

**Issue by jhzzzz** [Paciolan/remote-component#10]
Hi,

I use create react app, and the home page like below:

``` javascript
import _ from 'lodash'
import React, { Component } from 'react'

import styles from './index.module.css'
import { RemoteComponent } from '../../components/RemoteComponent'

const url = "https://raw.githubusercontent.com/Paciolan/remote-component/master/examples/remote-components/HelloWorld.js";
const HelloWorld = props => <RemoteComponent url={url} {...props} />;

class Home extends Component {
    render() {
        return (
            <div>
                <div className={styles.loginContainer}>
                    <div>START</div>
                    <HelloWorld name="Paciolan" />
                    <div>END</div>
                </div>
            </div>
        )
    }
}

export default Home
```

and i have follow the instruction to add webpack configs and other steps, when try to start the app, it show error like below:

![image](https://user-images.githubusercontent.com/6584445/97085079-ab781a80-164d-11eb-85ab-b54ab0eff216.png)

would you help to check where the problem is, thanks.

**Comment by jhzzzz** [comment]
solved by delete node_modules and retry yarn install.

**Comment by joelnet** [comment]
I have seen this error when using `npm link` or React not being marked as external in the web config. It's usually a symptom of two React versions running in the same project.
