### ISSUE TITLE
new Function in remote-module-loader cannot work with CSP restrictions

### ISSUE THREAD

**Issue by zhaobaiyu** [Paciolan/remote-component#13]
https://github.com/Paciolan/remote-module-loader/blob/9ce278cfc5f874548879c14cb018c1c08fc87e47/src/lib/loadRemoteModule.js#L25

With [CSP](https://developer.chrome.com/extensions/contentSecurityPolicy) restrictions, we cannot evaluate strings of JavaScript, and `new Function` is disabled, so that **Remote Component** cannot work.

Do we have any alternatives of this line, or any other solutions/suggests.

Thanks!

**Comment by joelnet** [comment]
Right now `remote-component` will not work in a CSP restricted website. Further research on CSP is required and we do not have a solution yet.

Look into Webpack's module federation. It offers similar features https://webpack.js.org/concepts/module-federation.

**Comment by joelnet** [comment]
At this point CSP isn't going to be supported until it's supported by [@paciolan/remote-module-loader](https://github.com/Paciolan/remote-module-loader].

I have updated the README to reflect this decision. https://github.com/Paciolan/remote-component#content-security-policy-csp

There is also an Alternatives section in the README.
