### ISSUE TITLE
Will the consumer app need to be rebuilt to get the changes made to the remote component?

### ISSUE THREAD

**Issue by Jammar** [Paciolan/remote-component#15]
This is a great project!!!

One question, just let me get this straight...

Will I be able to configure the remote component and have these changes made in the consuming-app without having to re-build it? The remote component will always be dynamically rendered and I will be able to adjust it, change it, update it... and the consumer app won't have to be re-built or re-deployed to have these changes made, yes?

🙏

**Comment by joelnet** [comment]
It sounds like you got it right. The remote component is imported at run time. Meaning the main app does not have to be rebuilt or redeployed when a remote component has been updated. Cheers 🍻

**Comment by joelnet** [comment]
I am closing this issue as it could become a [Discussion](https://github.com/Paciolan/remote-component/discussions)
