### ISSUE TITLE
Using import() syntax in dependency list

### ISSUE THREAD

**Issue by monmush** [Paciolan/remote-component#45]
Recently I have migrated out project prom CRA to ViteJS. As I understand, Vite does not support require() syntax so I have to make a little change in `remote-component.config.js` to use the import() instead.

`export const resolve = {
  react: import('react'),
  ['@filum-ai/ui']: import('@filum-ai/ui'),
  antd: import('antd'),
  ['react-query']: await import('react-query'),
  ['@ant-design/icons']: import('@ant-design/icons'),
}
`

However, it seems like there is something to do with the import and module system so remote-component can not resolve the dependencies

`error TypeError: o.default.createContext is not a function
    at eval (eval at <anonymous> (loadRemoteModule.ts:41), <anonymous>:3:26391)
    at loadRemoteModule.ts:42`
    
 @joelnet Do you have any idea or suggestion on regarding the issue?. I really appreciated your help. Thanks!

**Comment by joelnet** [comment]
Have a look at the section [Injecting Dependencies without Webpack](https://github.com/Paciolan/remote-component#injecting-dependencies-without-webpack). You should be able to use any bundler using this method.

As for the `remote-component.config.js` you can do something like this:


```javascript
import react from 'react';

export const resolve = {
  react
};
```
