### ISSUE TITLE
Issue creating a new Remote Component 

### ISSUE THREAD

**Issue by ashkorat** [Paciolan/remote-component#49]
Hi, I've been trying to create a new Remote Component for my project. It worked fine in the example but when I tried to create new Remote Component it didn't work. I tried to figure out the issue but no luck with that. here is my repository https://github.com/ashkorat/loginpanel It would be helpful if someone can help to figure out the issue. Thanks!

**Comment by joelnet** [comment]
Can you elaborate on "it didn't work". Did you get an error message? What happened and what was the expected result?
