### ISSUE TITLE
How to set module's import name？

### ISSUE THREAD

**Issue by blackraindrop** [Paciolan/remote-component#51]
Expected interface definitions

```ts
export interface UseRemoteComponentHook {
  (url: string, imports: string): [boolean, Error, (...unknown) => JSX.Element];
}
```

**Comment by joelnet** [comment]
I am not sure I fully understand the question. Could you elaborate a little bit?

**Comment by mkikets99** [comment]
@blackraindrop Is it an issue? Can you please provide some logs and code fragments for analizing whats wrong?

**Comment by joelnet** [comment]
@blackraindrop I just merged in this update. Test it and let me know if this is what you needed. Cheers 🍻
