### ISSUE TITLE
how can i use it with typescript

### ISSUE THREAD

**Issue by ckken** [Paciolan/remote-component#6]

**Comment by joelnet** [comment]
I haven't tried this in a TypeScript project, but it's my understanding that the process should be the same in either JS or TS. Were you getting some specific errors in your library?

**Comment by ckken** [comment]
i can use it with type check

**Comment by joelnet** [comment]
Currently the library is written in JavaScript and not TypeScript, so it doesn't have the type support that is in TypeScript. I have been looking into adding type support for the library but it's lower priority right now. But we may possibly add this in a future version.

**Comment by joelnet** [comment]
The project has recently been converted to TypeScript. This should mean the Types will be imported automatically when in a TypeScript project.

This change was added at https://github.com/Paciolan/remote-component/commit/c9442c45e435d5af3479c3d42aa363845ea0dd78
