### ISSUE TITLE
Auth in Header When Loading Remote Component

### ISSUE THREAD

**Issue by seikosantana** [Paciolan/remote-component#62]
Hi,

Thanks for your amazing work! I've been trying to implement a solution using Ionic with remote component to create dashboards system that is more loosely coupled to the main app, and after some tweaking, I finally get it working nicely.

However, is there a way to add Authorization headers during the fetch? The remote component files are behind a backend and if possible i wanted to apply auth.

**Comment by joelnet** [comment]
Yes! This can be done by using a custom fetcher. This way you'll have full control over the headers being sent.

Check out the example here: https://github.com/Paciolan/remote-component#custom-fetcher

In this example, I replaced the built in fetcher with axios. But you can replace the fetcher with your own implementation with auth headers.

```javascript
import axios from "axios";
import {
  createRemoteComponent,
  createRequires
} from "@paciolan/remote-component";
import { resolve } from "./remote-component.config.js";

const requires = createRequires(resolve);
const fetcher = url => axios.get(url).then(request => request.data);

export const RemoteComponent = createRemoteComponent({ requires, fetcher });
```

**Comment by seikosantana** [comment]
Oh thanks a lot, that does it!
