### ISSUE TITLE
Hot reload support with Remote component

### ISSUE THREAD

**Issue by Nishchit14** [Paciolan/remote-component#8]
Is there a way to review the changes in the `Remote Component` directly where it is rendered? It's quite needed in development time. In my case, I am developing UI library locally and rendering them in another app as `Remote Component`.

**Comment by joelnet** [comment]
You have to debug the remote component inside the remote component app and not inside the app consuming the remote component. We'd like to improve this in the future, but currently this is the only way.

If you are using the remote component starter kit, then check out the [Debugging](https://github.com/Paciolan/remote-component-starter#debugging) section for how to debug.

You can mock the props coming into the remote component by modifying `/src/webpack-dev-server.js`.

I'll be adding some clarity to the docs in the coming future, so right now you'll have to ask me if you have questions. 

I hope this helps a bit.
