### ISSUE TITLE
Remote component creation

### ISSUE THREAD

**Issue by miltonbo** [Paciolan/remote-component#9]
Hi there, initially let you know this project promises a lot, currently we are working on some dynamic content and probably it will help a lot. I was able to re-use those example components that you implemented, however I couldn't get it running from my end with my own remote component, I created a new project with CRA and react 16.3.1, however I faced the problem that webpack config is not published, it would require eject execution, ask you whether you could upload those resources that you used to create your examples. Thanks in advance.

**Comment by joelnet** [comment]
Hmm. I thought I was able to get this working in CRA without ejection. Did you follow the guide for CRA here? https://github.com/Paciolan/remote-component#create-react-app

Let me  know what problems you have with the guide and I'll try to help out.

**Comment by miltonbo** [comment]
I tried to follow it, however I think it's mixed configuration between react project and remote react component, that's why I'm asking you to provide that source code that you have used to create your examples: `HelloWorld.js`, `Time.js` and `Counter.js`.

**Comment by joelnet** [comment]
I spent a little time looking into this and the docs we have for CRA need expanding. We will have to make some modifications to the library to work better with CRA. Currently, you have to eject or use https://github.com/gsoft-inc/craco to expose the webpack.config.

I'll add this to my TODO list.

**Comment by hotpothot** [comment]
Hi @miltonbo, does eject works for you?
Hi @joelnet, I ejected the CRA I create to generate my own remote component, but I still hit "Unknown Error: ReferenceError: react is not defined". I am in the same boat with @miltonbo which I can have everything work correctly with the remotecomponent you created HelloWorld.js，but failed to create my own remote component following the instruction you have.
Can you share more details why lib doesn't work with CRA?

**Comment by joelnet** [comment]
So CRA hides a bunch of configuration files that remote component needs access too. Namely webpack.config.js. I also don't know what pieces should be added once it's ejected. So until we have figured out the best process for getting CRA working, CRA is unsupported.

I can tell you that it's on the near horizon and if I get some time to look into CRA, I'll try to provide some instructions. But right now I just don't know.

Though underneath CRA is webpack, so I know it'll work. I just don't know the exact settings yet.

**Comment by hotpothot** [comment]
Thanks @joelnet for clarfication!
I guess what I should try here are
1. create react app from [scratch ](https://medium.com/javascript-in-plain-english/a-guide-to-creating-a-react-app-without-create-react-app-5337c5ac2ea0)instead of npx create-react-app
2. follow the your [instruction ](https://github.com/Paciolan/remote-component#create-react-app)

**Comment by joelnet** [comment]
Ya for now that sounds great. I know the docs are lacking and it'd be nice to have a project that you can check out and run. These are things that I will be working on next 👍

**Comment by joelnet** [comment]
Okay, I was able to spend some time on this and I was able to put up some docs specific to CRA here. Looks like it's fine to use CRA without eject.

https://github.com/Paciolan/remote-component#create-react-app-cra

Cheers 🍻
